import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });
import Logo from "@/assets/images/download.jpg";
import Media from "@/assets/images/media-indonesia.png";
import { useState } from "react";
import Footer from "@/components/Footer";

export default function Home() {
  const [section, setSection] = useState(1);
  const [quote, setQuote] = useState(1);
  const [shown1, setShown1] = useState(false);
  const [shown2, setShown2] = useState(false);
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Header />
      <main className="pt-20">
        <section className="flex flex-row w-screen bg-violet-1000">
          <article className="flex flex-col p-20 w-1/2 text-white gap-3">
            <Image src={Logo} className="h-20" alt="logo2" />
            <div className="font-extrabold text-5xl">
              Sobat Kost, sahabatnya anak kos
            </div>
            <div className="text-xl">
              Semua yang anda butuhkan sebagai anak kos ada di sini. Kamar
              kosong, antar jemput, bersihkan kamar, semuanya ada
            </div>
            <div className="text-xl">
              Bahkan jika anda ingin mempromosikan kos, kami bisa membantu
            </div>
            <button className="bg-red-700 p-5 rounded-md text-lg">
              Daftar Sekarang
            </button>
          </article>
          <article className="w-1/2">
            <Image
              src={Logo}
              className="w-full rounded-bl-full rounded-tl-full"
              alt="homepage"
            />
          </article>
        </section>
        <section className="w-screen flex flex-row p-10">
          <article className="w-1/2 flex flex-col p-10 gap-5">
            <div className="text-5xl font-extrabold">
              Sobat Kos adalah start up mantap
            </div>
            <div className="text-xl">
              Sebagai aplikasi palugada untuk anak kos nomor 1 di Indonesia
              semenjak 2022, Sobatkos terhubung ke jutaan pencari kos di seluruh
              Dunia.
            </div>
            <Image src={Logo} className="w-full" alt="content-image" />
          </article>
          <article className="w-1/2 flex flex-col p-10">
            <div className="flex flex-row">
              <Image src={Logo} className="w-2/4" alt="content-image-2" />
              <Image src={Logo} className="w-2/4" alt="content-image-2" />
            </div>
            <div>
              <Image src={Logo} className="w-full" alt="content-image-2" />
            </div>
          </article>
        </section>
        <section className="p-20 flex flex-col gap-20 ">
          <article className="text-center text-5xl px-20">
            Bagaimana Kami Membantu Mengembangkan Bisnis Kos Anda?
          </article>
          <article className="flex flex-row items-center gap-10">
            <div className="flex flex-col items-center gap-5">
              <Image src={Logo} alt="content-image-3" />
              <div className="text-center">
                Menampilkan kos Anda kepada pencari kos dengan jumlah besar
              </div>
              <div className="text-center">7 juta pencari kos/bulan</div>
            </div>
            <div className="flex flex-col items-center gap-5">
              <Image src={Logo} alt="content-image-3" />
              <div className="text-center">
                Menampilkan kos Anda kepada pencari kos dengan jumlah besar
              </div>
              <div className="text-center">7 juta pencari kos/bulan</div>
            </div>
            <div className="flex flex-col items-center gap-5">
              <Image src={Logo} alt="content-image-3" />
              <div className="text-center">
                Menampilkan kos Anda kepada pencari kos dengan jumlah besar
              </div>
              <div className="text-center">7 juta pencari kos/bulan</div>
            </div>
          </article>
        </section>
        <section className="flex flex-row bg-pink-900 p-10 text-white">
          <article className="w-1/2 p-10 flex flex-col gap-10">
            <div>
              <Image src={Logo} className="h-10" alt="content-logo-2" />
            </div>
            <div className="text-5xl font-extrabold">
              Solusi mendapatkan pendapatan baru
            </div>
            <div className="flex flex-row items-center gap-7">
              <button
                className="text-black text-3xl bg-white w-14 h-14 rounded-full"
                onClick={() => {
                  section === 1 ? setSection(3) : setSection(section - 1);
                }}
              >
                &lt;
              </button>
              <div className="flex flex-row items-center gap-2">
                <div
                  className={`${
                    section === 1 ? "bg-white" : "bg-slate-500"
                  } w-2 h-2 rounded-full`}
                ></div>
                <div
                  className={`${
                    section === 2 ? "bg-white" : "bg-slate-500"
                  } w-2 h-2 rounded-full`}
                ></div>
                <div
                  className={`${
                    section === 3 ? "bg-white" : "bg-slate-500"
                  } w-2 h-2 rounded-full`}
                ></div>
              </div>
              <button
                className="text-black text-3xl bg-white w-12 h-12 rounded-full"
                onClick={() => {
                  section === 3 ? setSection(1) : setSection(section + 1);
                }}
              >
                &gt;
              </button>
            </div>
          </article>
          <article
            className={`w-1/2 p-10 ${
              section === 1 ? "flex" : "hidden"
            } flex-col gap-10`}
          >
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">Kamar Rasa 1</p>
              <p>
                Gerai makanan online dengan berbagai brand kuliner dalam 1
                outlet
              </p>
            </div>
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">Kamar Rasa</p>
              <p>
                Gerai makanan online dengan berbagai brand kuliner dalam 1
                outlet
              </p>
            </div>
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">Kamar Rasa</p>
              <p>
                Gerai makanan online dengan berbagai brand kuliner dalam 1
                outlet
              </p>
            </div>
          </article>
          <article
            className={`w-1/2 p-10 ${
              section === 2 ? "flex" : "hidden"
            } flex-col gap-10`}
          >
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">Kamar Rasa 2</p>
              <p>
                Gerai makanan online dengan berbagai brand kuliner dalam 1
                outlet
              </p>
            </div>
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">Kamar Rasa</p>
              <p>
                Gerai makanan online dengan berbagai brand kuliner dalam 1
                outlet
              </p>
            </div>
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">Kamar Rasa</p>
              <p>
                Gerai makanan online dengan berbagai brand kuliner dalam 1
                outlet
              </p>
            </div>
          </article>
          <article
            className={`w-1/2 p-10 ${
              section === 3 ? "flex" : "hidden"
            } flex-col gap-10`}
          >
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">Kamar Rasa 3</p>
              <p>
                Gerai makanan online dengan berbagai brand kuliner dalam 1
                outlet
              </p>
            </div>
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">Kamar Rasa</p>
              <p>
                Gerai makanan online dengan berbagai brand kuliner dalam 1
                outlet
              </p>
            </div>
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">Kamar Rasa</p>
              <p>
                Gerai makanan online dengan berbagai brand kuliner dalam 1
                outlet
              </p>
            </div>
          </article>
        </section>
        <section className="flex flex-row bg-purple-900 p-10 text-white">
          <article className="w-1/2 p-10 flex flex-col gap-10">
            <div className="text-5xl font-extrabold">Kata pemilik kost</div>
            <div className="flex flex-row items-center gap-7">
              <button
                className="text-black text-3xl bg-white w-14 h-14 rounded-full"
                onClick={() => {
                  quote === 1 ? setQuote(3) : setQuote(quote - 1);
                }}
              >
                &lt;
              </button>
              <div className="flex flex-row items-center gap-2">
                <div
                  className={`${
                    quote === 1 ? "bg-white" : "bg-slate-500"
                  } w-2 h-2 rounded-full`}
                ></div>
                <div
                  className={`${
                    quote === 2 ? "bg-white" : "bg-slate-500"
                  } w-2 h-2 rounded-full`}
                ></div>
                <div
                  className={`${
                    quote === 3 ? "bg-white" : "bg-slate-500"
                  } w-2 h-2 rounded-full`}
                ></div>
              </div>
              <button
                className="text-black text-3xl bg-white w-12 h-12 rounded-full"
                onClick={() => {
                  quote === 3 ? setQuote(1) : setQuote(quote + 1);
                }}
              >
                &gt;
              </button>
            </div>
          </article>
          <article
            className={`w-1/2 p-10 ${
              quote === 1 ? "flex" : "hidden"
            } flex-col gap-10`}
          >
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">
                “Saya memilih kerja sama dengan Mamikos karena saya sering
                mendengar mamikos dari internet dan saya merasa branding nya
                bagus. Saya merasa cukup puas setelah bergabung dengan singgah
                sini, karena saya tidak perlu repot untuk menghandle kost saya”.
              </p>
              <div>
                <p className="font-extrabold">Erni</p>
                <p>
                  Pemilik Kost Singgahsini Wisma KS23 Setiabudi Jakarta Selatan
                </p>
              </div>
            </div>
          </article>
          <article
            className={`w-1/2 p-10 ${
              quote === 2 ? "flex" : "hidden"
            } flex-col gap-10`}
          >
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">
                “Saya memilih kerja sama dengan Mamikos karena saya sering
                mendengar mamikos dari internet dan saya merasa branding nya
                bagus. Saya merasa cukup puas setelah bergabung dengan singgah
                sini, karena saya tidak perlu repot untuk menghandle kost saya”.
              </p>
              <div>
                <p className="font-extrabold">Erni</p>
                <p>
                  Pemilik Kost Singgahsini Wisma KS23 Setiabudi Jakarta Selatan
                </p>
              </div>
            </div>
          </article>
          <article
            className={`w-1/2 p-10 ${
              quote === 3 ? "flex" : "hidden"
            } flex-col gap-10`}
          >
            <div className="flex flex-col gap-3">
              <p className="font-bold text-xl">
                “Saya memilih kerja sama dengan Mamikos karena saya sering
                mendengar mamikos dari internet dan saya merasa branding nya
                bagus. Saya merasa cukup puas setelah bergabung dengan singgah
                sini, karena saya tidak perlu repot untuk menghandle kost saya”.
              </p>
              <div>
                <p className="font-extrabold">Erni</p>
                <p>
                  Pemilik Kost Singgahsini Wisma KS23 Setiabudi Jakarta Selatan
                </p>
              </div>
            </div>
          </article>
        </section>
        <section className="flex flex-col items-center p-20 gap-10">
          <div className="font-extrabold text-6xl">Diliput oleh</div>
          <Image src={Media} alt="media" />
        </section>
        <section className="flex flex-row w-screen bg-purple-900">
          <article className="w-5/12">
            <Image className="w-full h-full" src={Logo} alt="article" />
          </article>
          <article className="flex flex-col w-7/12 text-white p-10 gap-10">
            <div className="text-5xl">Sobatkost</div>
            <div className="text-5xl">
              Mari Bicarakan Solusi untuk Mengembangkan Bisnis Kos Anda
            </div>
            <div className="text-xl pr-20">
              Daftarkan kos Anda di Singgahsini atau Apik, dan Anda juga akan
              terdaftar ke dalam komunitas pemilik kos Mamikos di seluruh
              Indonesia.
            </div>
            <button className="bg-red-700 p-5 rounded-md text-lg">
              Daftar Sekarang
            </button>
          </article>
        </section>
        <section className="flex flex-col px-60 py-20 gap-10">
          <div className="text-5xl font-extrabold">
            Tanya Jawab Seputar Sobatkos
          </div>
          <div className="flex flex-col gap-1">
            <button
              className="flex flex-row justify-between text-2xl text-start"
              onClick={() => {
                setShown1(!shown1);
              }}
            >
              <div className="font-extrabold">
                Apa bedanya Singgahsini dengan MamiRooms?
              </div>
              <div>V</div>
            </button>
            <p className={`${shown1 ? "" : "hidden"}`}>
              Singgahsini adalah wajah baru MamiRooms. Layanan yang ditawarkan
              secara keseluruhan masih sama, hanya ada perubahan pada nama dan
              logo, serta penambahan produk baru yaitu Apik.
            </p>
          </div>
          <div className="flex flex-col gap-1">
            <button
              className="flex flex-row justify-between text-2xl text-start"
              onClick={() => {
                setShown2(!shown2);
              }}
            >
              <div className="font-extrabold">
                Apa bedanya Singgahsini dengan MamiRooms?
              </div>
              <div>V</div>
            </button>
            <p className={`${shown2 ? "" : "hidden"}`}>
              Singgahsini adalah wajah baru MamiRooms. Layanan yang ditawarkan
              secara keseluruhan masih sama, hanya ada perubahan pada nama dan
              logo, serta penambahan produk baru yaitu Apik.
            </p>
          </div>
        </section>
        <section className="flex flex-col p-20 items-center text-white bg-rose-800 gap-8">
          <div className="text-7xl font-extrabold">
            Ingin tahu lebih lanjut?
          </div>
          <div>
            Download brosur Singgahsini dan Apik atau kunjungi Pusat Bantuan.
          </div>
          <button className="bg-white text-black p-4 rounded-xl">
            Pusat Bantuan &rarr;
          </button>
        </section>
      </main>
      <Footer />
    </>
  );
}
